/*
 * 千帆SDK
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baidubce.sdc.sdk.model.qianfan;

import java.util.Objects;
import com.baidubce.sdc.sdk.model.qianfan.ChatFunctionCall;
import com.baidubce.sdc.sdk.model.qianfan.ChatSearchInfo;
import com.baidubce.sdc.sdk.model.qianfan.Usage;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.baidubce.sdc.sdk.JSON;

/**
 * ChatResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.BaiduCtsQianfanJavaCodegen")
public class ChatResponse {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_OBJECT = "object";
  @SerializedName(SERIALIZED_NAME_OBJECT)
  private String _object;

  public static final String SERIALIZED_NAME_CREATED = "created";
  @SerializedName(SERIALIZED_NAME_CREATED)
  private Integer created;

  public static final String SERIALIZED_NAME_SENTENCE_ID = "sentence_id";
  @SerializedName(SERIALIZED_NAME_SENTENCE_ID)
  private Integer sentenceId;

  public static final String SERIALIZED_NAME_IS_END = "is_end";
  @SerializedName(SERIALIZED_NAME_IS_END)
  private Boolean isEnd;

  public static final String SERIALIZED_NAME_IS_TRUNCATED = "is_truncated";
  @SerializedName(SERIALIZED_NAME_IS_TRUNCATED)
  private Boolean isTruncated;

  public static final String SERIALIZED_NAME_FINISH_REASON = "finish_reason";
  @SerializedName(SERIALIZED_NAME_FINISH_REASON)
  private String finishReason;

  public static final String SERIALIZED_NAME_SEARCH_INFO = "search_info";
  @SerializedName(SERIALIZED_NAME_SEARCH_INFO)
  private ChatSearchInfo searchInfo;

  public static final String SERIALIZED_NAME_RESULT = "result";
  @SerializedName(SERIALIZED_NAME_RESULT)
  private String result;

  public static final String SERIALIZED_NAME_NEED_CLEAR_HISTORY = "need_clear_history";
  @SerializedName(SERIALIZED_NAME_NEED_CLEAR_HISTORY)
  private Boolean needClearHistory;

  public static final String SERIALIZED_NAME_FLAG = "flag";
  @SerializedName(SERIALIZED_NAME_FLAG)
  private Integer flag;

  public static final String SERIALIZED_NAME_BAN_ROUND = "ban_round";
  @SerializedName(SERIALIZED_NAME_BAN_ROUND)
  private Integer banRound;

  public static final String SERIALIZED_NAME_USAGE = "usage";
  @SerializedName(SERIALIZED_NAME_USAGE)
  private Usage usage;

  public static final String SERIALIZED_NAME_FUNCTION_CALL = "function_call";
  @SerializedName(SERIALIZED_NAME_FUNCTION_CALL)
  private ChatFunctionCall functionCall;

  public ChatResponse() {
  }

  public ChatResponse id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * 本轮对话的id
   * @return id
  **/
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public ChatResponse _object(String _object) {
    
    this._object = _object;
    return this;
  }

   /**
   * 回包类型 chat.completion：多轮对话返回
   * @return _object
  **/
  @javax.annotation.Nullable
  public String getObject() {
    return _object;
  }


  public void setObject(String _object) {
    this._object = _object;
  }


  public ChatResponse created(Integer created) {
    
    this.created = created;
    return this;
  }

   /**
   * 时间戳
   * @return created
  **/
  @javax.annotation.Nullable
  public Integer getCreated() {
    return created;
  }


  public void setCreated(Integer created) {
    this.created = created;
  }


  public ChatResponse sentenceId(Integer sentenceId) {
    
    this.sentenceId = sentenceId;
    return this;
  }

   /**
   * 表示当前子句的序号。只有在流式接口模式下会返回该字段
   * @return sentenceId
  **/
  @javax.annotation.Nullable
  public Integer getSentenceId() {
    return sentenceId;
  }


  public void setSentenceId(Integer sentenceId) {
    this.sentenceId = sentenceId;
  }


  public ChatResponse isEnd(Boolean isEnd) {
    
    this.isEnd = isEnd;
    return this;
  }

   /**
   * 表示当前子句是否是最后一句。只有在流式接口模式下会返回该字段
   * @return isEnd
  **/
  @javax.annotation.Nullable
  public Boolean getIsEnd() {
    return isEnd;
  }


  public void setIsEnd(Boolean isEnd) {
    this.isEnd = isEnd;
  }


  public ChatResponse isTruncated(Boolean isTruncated) {
    
    this.isTruncated = isTruncated;
    return this;
  }

   /**
   * 当前生成的结果是否被截断
   * @return isTruncated
  **/
  @javax.annotation.Nullable
  public Boolean getIsTruncated() {
    return isTruncated;
  }


  public void setIsTruncated(Boolean isTruncated) {
    this.isTruncated = isTruncated;
  }


  public ChatResponse finishReason(String finishReason) {
    
    this.finishReason = finishReason;
    return this;
  }

   /**
   * 输出内容标识，说明： · normal：输出内容完全由大模型生成，未触发截断、替换 · stop：输出结果命中入参stop中指定的字段后被截断 · length：达到了最大的token数，根据EB返回结果is_truncated来截断 · content_filter：输出内容被截断、兜底、替换为**等 · function_call：调用了funtion call功能
   * @return finishReason
  **/
  @javax.annotation.Nullable
  public String getFinishReason() {
    return finishReason;
  }


  public void setFinishReason(String finishReason) {
    this.finishReason = finishReason;
  }


  public ChatResponse searchInfo(ChatSearchInfo searchInfo) {
    
    this.searchInfo = searchInfo;
    return this;
  }

   /**
   * Get searchInfo
   * @return searchInfo
  **/
  @javax.annotation.Nullable
  public ChatSearchInfo getSearchInfo() {
    return searchInfo;
  }


  public void setSearchInfo(ChatSearchInfo searchInfo) {
    this.searchInfo = searchInfo;
  }


  public ChatResponse result(String result) {
    
    this.result = result;
    return this;
  }

   /**
   * 对话返回结果
   * @return result
  **/
  @javax.annotation.Nullable
  public String getResult() {
    return result;
  }


  public void setResult(String result) {
    this.result = result;
  }


  public ChatResponse needClearHistory(Boolean needClearHistory) {
    
    this.needClearHistory = needClearHistory;
    return this;
  }

   /**
   * 表示用户输入是否存在安全，是否关闭当前会话，清理历史会话信息 · true：是，表示用户输入存在安全风险，建议关闭当前会话，清理历史会话信息 · false：否，表示用户输入无安全风险
   * @return needClearHistory
  **/
  @javax.annotation.Nullable
  public Boolean getNeedClearHistory() {
    return needClearHistory;
  }


  public void setNeedClearHistory(Boolean needClearHistory) {
    this.needClearHistory = needClearHistory;
  }


  public ChatResponse flag(Integer flag) {
    
    this.flag = flag;
    return this;
  }

   /**
   * 说明： · 0：正常返回 · 其他：非正常
   * @return flag
  **/
  @javax.annotation.Nullable
  public Integer getFlag() {
    return flag;
  }


  public void setFlag(Integer flag) {
    this.flag = flag;
  }


  public ChatResponse banRound(Integer banRound) {
    
    this.banRound = banRound;
    return this;
  }

   /**
   * 当need_clear_history为true时，此字段会告知第几轮对话有敏感信息，如果是当前问题，ban_round&#x3D;-1
   * @return banRound
  **/
  @javax.annotation.Nullable
  public Integer getBanRound() {
    return banRound;
  }


  public void setBanRound(Integer banRound) {
    this.banRound = banRound;
  }


  public ChatResponse usage(Usage usage) {
    
    this.usage = usage;
    return this;
  }

   /**
   * Get usage
   * @return usage
  **/
  @javax.annotation.Nullable
  public Usage getUsage() {
    return usage;
  }


  public void setUsage(Usage usage) {
    this.usage = usage;
  }


  public ChatResponse functionCall(ChatFunctionCall functionCall) {
    
    this.functionCall = functionCall;
    return this;
  }

   /**
   * Get functionCall
   * @return functionCall
  **/
  @javax.annotation.Nullable
  public ChatFunctionCall getFunctionCall() {
    return functionCall;
  }


  public void setFunctionCall(ChatFunctionCall functionCall) {
    this.functionCall = functionCall;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the ChatResponse instance itself
   */
  public ChatResponse putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChatResponse chatResponse = (ChatResponse) o;
    return Objects.equals(this.id, chatResponse.id) &&
        Objects.equals(this._object, chatResponse._object) &&
        Objects.equals(this.created, chatResponse.created) &&
        Objects.equals(this.sentenceId, chatResponse.sentenceId) &&
        Objects.equals(this.isEnd, chatResponse.isEnd) &&
        Objects.equals(this.isTruncated, chatResponse.isTruncated) &&
        Objects.equals(this.finishReason, chatResponse.finishReason) &&
        Objects.equals(this.searchInfo, chatResponse.searchInfo) &&
        Objects.equals(this.result, chatResponse.result) &&
        Objects.equals(this.needClearHistory, chatResponse.needClearHistory) &&
        Objects.equals(this.flag, chatResponse.flag) &&
        Objects.equals(this.banRound, chatResponse.banRound) &&
        Objects.equals(this.usage, chatResponse.usage) &&
        Objects.equals(this.functionCall, chatResponse.functionCall)&&
        Objects.equals(this.additionalProperties, chatResponse.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, _object, created, sentenceId, isEnd, isTruncated, finishReason, searchInfo, result, needClearHistory, flag, banRound, usage, functionCall, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChatResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    _object: ").append(toIndentedString(_object)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    sentenceId: ").append(toIndentedString(sentenceId)).append("\n");
    sb.append("    isEnd: ").append(toIndentedString(isEnd)).append("\n");
    sb.append("    isTruncated: ").append(toIndentedString(isTruncated)).append("\n");
    sb.append("    finishReason: ").append(toIndentedString(finishReason)).append("\n");
    sb.append("    searchInfo: ").append(toIndentedString(searchInfo)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("    needClearHistory: ").append(toIndentedString(needClearHistory)).append("\n");
    sb.append("    flag: ").append(toIndentedString(flag)).append("\n");
    sb.append("    banRound: ").append(toIndentedString(banRound)).append("\n");
    sb.append("    usage: ").append(toIndentedString(usage)).append("\n");
    sb.append("    functionCall: ").append(toIndentedString(functionCall)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("object");
    openapiFields.add("created");
    openapiFields.add("sentence_id");
    openapiFields.add("is_end");
    openapiFields.add("is_truncated");
    openapiFields.add("finish_reason");
    openapiFields.add("search_info");
    openapiFields.add("result");
    openapiFields.add("need_clear_history");
    openapiFields.add("flag");
    openapiFields.add("ban_round");
    openapiFields.add("usage");
    openapiFields.add("function_call");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to ChatResponse
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ChatResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ChatResponse is not found in the empty JSON string", ChatResponse.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("object") != null && !jsonObj.get("object").isJsonNull()) && !jsonObj.get("object").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `object` to be a primitive type in the JSON string but got `%s`", jsonObj.get("object").toString()));
      }
      if ((jsonObj.get("finish_reason") != null && !jsonObj.get("finish_reason").isJsonNull()) && !jsonObj.get("finish_reason").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `finish_reason` to be a primitive type in the JSON string but got `%s`", jsonObj.get("finish_reason").toString()));
      }
      if ((jsonObj.get("result") != null && !jsonObj.get("result").isJsonNull()) && !jsonObj.get("result").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `result` to be a primitive type in the JSON string but got `%s`", jsonObj.get("result").toString()));
      }
      // validate the optional field `usage`
      if (jsonObj.get("usage") != null && !jsonObj.get("usage").isJsonNull()) {
        Usage.validateJsonElement(jsonObj.get("usage"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ChatResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ChatResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ChatResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ChatResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<ChatResponse>() {
           @Override
           public void write(JsonWriter out, ChatResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public ChatResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             ChatResponse instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ChatResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ChatResponse
  * @throws IOException if the JSON string is invalid with respect to ChatResponse
  */
  public static ChatResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ChatResponse.class);
  }

 /**
  * Convert an instance of ChatResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

