/*
 * 千帆SDK
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baidubce.sdc.sdk.model.qianfan;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets CompletionLlmEnum
 */
@JsonAdapter(CompletionLlmEnum.Adapter.class)
public enum CompletionLlmEnum {
  
  SQLCoder_7B("sqlcoder_7b"),
  
  CodeLlama_7b_Instruct("codellama_7b_instruct");

  private String value;

  CompletionLlmEnum(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static CompletionLlmEnum fromValue(String value) {
    for (CompletionLlmEnum b : CompletionLlmEnum.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<CompletionLlmEnum> {
    @Override
    public void write(final JsonWriter jsonWriter, final CompletionLlmEnum enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public CompletionLlmEnum read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return CompletionLlmEnum.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    CompletionLlmEnum.fromValue(value);
  }
}

