/*
 * 千帆SDK
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Baiducloud.SDK.Model.Qianfan;
using Baiducloud.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Baiducloud.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing ChatFunctionCall
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ChatFunctionCallTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ChatFunctionCall
        //private ChatFunctionCall instance;

        public ChatFunctionCallTests()
        {
            // TODO uncomment below to create an instance of ChatFunctionCall
            //instance = new ChatFunctionCall();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ChatFunctionCall
        /// </summary>
        [Fact]
        public void ChatFunctionCallInstanceTest()
        {
            // TODO uncomment below to test "IsType" ChatFunctionCall
            //Assert.IsType<ChatFunctionCall>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Arguments'
        /// </summary>
        [Fact]
        public void ArgumentsTest()
        {
            // TODO unit test for the property 'Arguments'
        }

        /// <summary>
        /// Test the property 'Thoughts'
        /// </summary>
        [Fact]
        public void ThoughtsTest()
        {
            // TODO unit test for the property 'Thoughts'
        }
    }
}
