/*
 * 千帆SDK
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Baiducloud.SDK.Model.Qianfan;
using Baiducloud.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Baiducloud.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing ChatLlm
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ChatLlmTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ChatLlm
        //private ChatLlm instance;

        public ChatLlmTests()
        {
            // TODO uncomment below to create an instance of ChatLlm
            //instance = new ChatLlm();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ChatLlm
        /// </summary>
        [Fact]
        public void ChatLlmInstanceTest()
        {
            // TODO uncomment below to test "IsType" ChatLlm
            //Assert.IsType<ChatLlm>(instance);
        }
    }
}
