/*
 * 千帆SDK
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Baiducloud.SDK.Model.Qianfan;
using Baiducloud.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Baiducloud.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing ChatRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ChatRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ChatRequest
        //private ChatRequest instance;

        public ChatRequestTests()
        {
            // TODO uncomment below to create an instance of ChatRequest
            //instance = new ChatRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ChatRequest
        /// </summary>
        [Fact]
        public void ChatRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ChatRequest
            //Assert.IsType<ChatRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Messages'
        /// </summary>
        [Fact]
        public void MessagesTest()
        {
            // TODO unit test for the property 'Messages'
        }

        /// <summary>
        /// Test the property 'Functions'
        /// </summary>
        [Fact]
        public void FunctionsTest()
        {
            // TODO unit test for the property 'Functions'
        }

        /// <summary>
        /// Test the property 'Temperature'
        /// </summary>
        [Fact]
        public void TemperatureTest()
        {
            // TODO unit test for the property 'Temperature'
        }

        /// <summary>
        /// Test the property 'TopP'
        /// </summary>
        [Fact]
        public void TopPTest()
        {
            // TODO unit test for the property 'TopP'
        }

        /// <summary>
        /// Test the property 'PenaltyScore'
        /// </summary>
        [Fact]
        public void PenaltyScoreTest()
        {
            // TODO unit test for the property 'PenaltyScore'
        }

        /// <summary>
        /// Test the property 'Stream'
        /// </summary>
        [Fact]
        public void StreamTest()
        {
            // TODO unit test for the property 'Stream'
        }

        /// <summary>
        /// Test the property 'VarSystem'
        /// </summary>
        [Fact]
        public void VarSystemTest()
        {
            // TODO unit test for the property 'VarSystem'
        }

        /// <summary>
        /// Test the property 'Stop'
        /// </summary>
        [Fact]
        public void StopTest()
        {
            // TODO unit test for the property 'Stop'
        }

        /// <summary>
        /// Test the property 'DisableSearch'
        /// </summary>
        [Fact]
        public void DisableSearchTest()
        {
            // TODO unit test for the property 'DisableSearch'
        }

        /// <summary>
        /// Test the property 'EnableCitation'
        /// </summary>
        [Fact]
        public void EnableCitationTest()
        {
            // TODO unit test for the property 'EnableCitation'
        }

        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
    }
}
