/*
 * 千帆SDK
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Baiducloud.SDK.Model.Qianfan;
using Baiducloud.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Baiducloud.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing ImageData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ImageDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ImageData
        //private ImageData instance;

        public ImageDataTests()
        {
            // TODO uncomment below to create an instance of ImageData
            //instance = new ImageData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ImageData
        /// </summary>
        [Fact]
        public void ImageDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" ImageData
            //Assert.IsType<ImageData>(instance);
        }

        /// <summary>
        /// Test the property 'VarObject'
        /// </summary>
        [Fact]
        public void VarObjectTest()
        {
            // TODO unit test for the property 'VarObject'
        }

        /// <summary>
        /// Test the property 'B64Image'
        /// </summary>
        [Fact]
        public void B64ImageTest()
        {
            // TODO unit test for the property 'B64Image'
        }

        /// <summary>
        /// Test the property 'Index'
        /// </summary>
        [Fact]
        public void IndexTest()
        {
            // TODO unit test for the property 'Index'
        }
    }
}
