/*
 * 千帆SDK
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Baiducloud.SDK.Model.Qianfan;
using Baiducloud.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Baiducloud.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing ImageRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ImageRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ImageRequest
        //private ImageRequest instance;

        public ImageRequestTests()
        {
            // TODO uncomment below to create an instance of ImageRequest
            //instance = new ImageRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ImageRequest
        /// </summary>
        [Fact]
        public void ImageRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ImageRequest
            //Assert.IsType<ImageRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Prompt'
        /// </summary>
        [Fact]
        public void PromptTest()
        {
            // TODO unit test for the property 'Prompt'
        }

        /// <summary>
        /// Test the property 'NegativePrompt'
        /// </summary>
        [Fact]
        public void NegativePromptTest()
        {
            // TODO unit test for the property 'NegativePrompt'
        }

        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Fact]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }

        /// <summary>
        /// Test the property 'N'
        /// </summary>
        [Fact]
        public void NTest()
        {
            // TODO unit test for the property 'N'
        }

        /// <summary>
        /// Test the property 'Steps'
        /// </summary>
        [Fact]
        public void StepsTest()
        {
            // TODO unit test for the property 'Steps'
        }

        /// <summary>
        /// Test the property 'SamplerIndex'
        /// </summary>
        [Fact]
        public void SamplerIndexTest()
        {
            // TODO unit test for the property 'SamplerIndex'
        }

        /// <summary>
        /// Test the property 'Seed'
        /// </summary>
        [Fact]
        public void SeedTest()
        {
            // TODO unit test for the property 'Seed'
        }

        /// <summary>
        /// Test the property 'CfgScale'
        /// </summary>
        [Fact]
        public void CfgScaleTest()
        {
            // TODO unit test for the property 'CfgScale'
        }

        /// <summary>
        /// Test the property 'Style'
        /// </summary>
        [Fact]
        public void StyleTest()
        {
            // TODO unit test for the property 'Style'
        }

        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
    }
}
