/*
 * 千帆SDK
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Baiducloud.SDK.Model.Qianfan;
using Baiducloud.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Baiducloud.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing PluginRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PluginRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PluginRequest
        //private PluginRequest instance;

        public PluginRequestTests()
        {
            // TODO uncomment below to create an instance of PluginRequest
            //instance = new PluginRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PluginRequest
        /// </summary>
        [Fact]
        public void PluginRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" PluginRequest
            //Assert.IsType<PluginRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Query'
        /// </summary>
        [Fact]
        public void QueryTest()
        {
            // TODO unit test for the property 'Query'
        }

        /// <summary>
        /// Test the property 'Plugins'
        /// </summary>
        [Fact]
        public void PluginsTest()
        {
            // TODO unit test for the property 'Plugins'
        }

        /// <summary>
        /// Test the property 'Stream'
        /// </summary>
        [Fact]
        public void StreamTest()
        {
            // TODO unit test for the property 'Stream'
        }

        /// <summary>
        /// Test the property 'Llm'
        /// </summary>
        [Fact]
        public void LlmTest()
        {
            // TODO unit test for the property 'Llm'
        }

        /// <summary>
        /// Test the property 'InputVariables'
        /// </summary>
        [Fact]
        public void InputVariablesTest()
        {
            // TODO unit test for the property 'InputVariables'
        }

        /// <summary>
        /// Test the property 'History'
        /// </summary>
        [Fact]
        public void HistoryTest()
        {
            // TODO unit test for the property 'History'
        }

        /// <summary>
        /// Test the property 'Verbose'
        /// </summary>
        [Fact]
        public void VerboseTest()
        {
            // TODO unit test for the property 'Verbose'
        }
    }
}
