/*
 * 千帆SDK
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Baiducloud.SDK.Model.Qianfan;
using Baiducloud.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Baiducloud.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing Usage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UsageTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Usage
        //private Usage instance;

        public UsageTests()
        {
            // TODO uncomment below to create an instance of Usage
            //instance = new Usage();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Usage
        /// </summary>
        [Fact]
        public void UsageInstanceTest()
        {
            // TODO uncomment below to test "IsType" Usage
            //Assert.IsType<Usage>(instance);
        }

        /// <summary>
        /// Test the property 'PromptTokens'
        /// </summary>
        [Fact]
        public void PromptTokensTest()
        {
            // TODO unit test for the property 'PromptTokens'
        }

        /// <summary>
        /// Test the property 'CompletionTokens'
        /// </summary>
        [Fact]
        public void CompletionTokensTest()
        {
            // TODO unit test for the property 'CompletionTokens'
        }

        /// <summary>
        /// Test the property 'TotalTokens'
        /// </summary>
        [Fact]
        public void TotalTokensTest()
        {
            // TODO unit test for the property 'TotalTokens'
        }
    }
}
