/*
 * 千帆SDK
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baidubce.sdc.sdk.model.qianfan;

import com.baidubce.sdc.sdk.model.qianfan.ChatFunctionCall;
import com.baidubce.sdc.sdk.model.qianfan.ChatSearchInfo;
import com.baidubce.sdc.sdk.model.qianfan.Usage;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ChatResponse
 */
public class ChatResponseTest {
    private final ChatResponse model = new ChatResponse();

    /**
     * Model tests for ChatResponse
     */
    @Test
    public void testChatResponse() {
        // TODO: test ChatResponse
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property '_object'
     */
    @Test
    public void _objectTest() {
        // TODO: test _object
    }

    /**
     * Test the property 'created'
     */
    @Test
    public void createdTest() {
        // TODO: test created
    }

    /**
     * Test the property 'sentenceId'
     */
    @Test
    public void sentenceIdTest() {
        // TODO: test sentenceId
    }

    /**
     * Test the property 'isEnd'
     */
    @Test
    public void isEndTest() {
        // TODO: test isEnd
    }

    /**
     * Test the property 'isTruncated'
     */
    @Test
    public void isTruncatedTest() {
        // TODO: test isTruncated
    }

    /**
     * Test the property 'finishReason'
     */
    @Test
    public void finishReasonTest() {
        // TODO: test finishReason
    }

    /**
     * Test the property 'searchInfo'
     */
    @Test
    public void searchInfoTest() {
        // TODO: test searchInfo
    }

    /**
     * Test the property 'result'
     */
    @Test
    public void resultTest() {
        // TODO: test result
    }

    /**
     * Test the property 'needClearHistory'
     */
    @Test
    public void needClearHistoryTest() {
        // TODO: test needClearHistory
    }

    /**
     * Test the property 'flag'
     */
    @Test
    public void flagTest() {
        // TODO: test flag
    }

    /**
     * Test the property 'banRound'
     */
    @Test
    public void banRoundTest() {
        // TODO: test banRound
    }

    /**
     * Test the property 'usage'
     */
    @Test
    public void usageTest() {
        // TODO: test usage
    }

    /**
     * Test the property 'functionCall'
     */
    @Test
    public void functionCallTest() {
        // TODO: test functionCall
    }

}
