/*
 * 千帆SDK
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baidubce.sdc.sdk.model.qianfan;

import com.baidubce.sdc.sdk.model.qianfan.EmbeddingLlmEnum;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for EmbeddingLlm
 */
public class EmbeddingLlmTest {
    private final EmbeddingLlm model = new EmbeddingLlm();

    /**
     * Model tests for EmbeddingLlm
     */
    @Test
    public void testEmbeddingLlm() {
        // TODO: test EmbeddingLlm
    }

}
