/*
 * 千帆SDK
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baidubce.sdc.sdk.model.qianfan;

import com.baidubce.sdc.sdk.model.qianfan.ChatMessage;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PluginRequest
 */
public class PluginRequestTest {
    private final PluginRequest model = new PluginRequest();

    /**
     * Model tests for PluginRequest
     */
    @Test
    public void testPluginRequest() {
        // TODO: test PluginRequest
    }

    /**
     * Test the property 'query'
     */
    @Test
    public void queryTest() {
        // TODO: test query
    }

    /**
     * Test the property 'plugins'
     */
    @Test
    public void pluginsTest() {
        // TODO: test plugins
    }

    /**
     * Test the property 'stream'
     */
    @Test
    public void streamTest() {
        // TODO: test stream
    }

    /**
     * Test the property 'llm'
     */
    @Test
    public void llmTest() {
        // TODO: test llm
    }

    /**
     * Test the property 'inputVariables'
     */
    @Test
    public void inputVariablesTest() {
        // TODO: test inputVariables
    }

    /**
     * Test the property 'history'
     */
    @Test
    public void historyTest() {
        // TODO: test history
    }

    /**
     * Test the property 'verbose'
     */
    @Test
    public void verboseTest() {
        // TODO: test verbose
    }

}
