/*
 * 千帆SDK
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Baiducloud.SDK.Client.FileParameter;
using OpenAPIDateConverter = Baiducloud.SDK.Client.OpenAPIDateConverter;
using Baiducloud.SDK.Client;

namespace Baiducloud.SDK.Model.Qianfan
{
    /// <summary>
    /// Defines ChatLlmEnum
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ChatLlmEnum
    {
        /// <summary>
        /// Enum ERNIE_Bot_4 for value: completions_pro
        /// </summary>
        [EnumMember(Value = "completions_pro")]
        ERNIE_Bot_4 = 1,

        /// <summary>
        /// Enum ERNIE_Bot_8k for value: ernie_bot_8k
        /// </summary>
        [EnumMember(Value = "ernie_bot_8k")]
        ERNIE_Bot_8k = 2,

        /// <summary>
        /// Enum ERNIE_Bot for value: completions
        /// </summary>
        [EnumMember(Value = "completions")]
        ERNIE_Bot = 3,

        /// <summary>
        /// Enum ERNIE_Bot_turbo for value: eb-instant
        /// </summary>
        [EnumMember(Value = "eb-instant")]
        ERNIE_Bot_turbo = 4,

        /// <summary>
        /// Enum ERNIE_Bot_turbo_AI for value: ai_apaas
        /// </summary>
        [EnumMember(Value = "ai_apaas")]
        ERNIE_Bot_turbo_AI = 5,

        /// <summary>
        /// Enum Yi_34B_Chat for value: yi_34b_chat
        /// </summary>
        [EnumMember(Value = "yi_34b_chat")]
        Yi_34B_Chat = 6,

        /// <summary>
        /// Enum BLOOMZ_7B for value: bloomz_7b1
        /// </summary>
        [EnumMember(Value = "bloomz_7b1")]
        BLOOMZ_7B = 7,

        /// <summary>
        /// Enum Qianfan_BLOOMZ_7B_compressed for value: qianfan_bloomz_7b_compressed
        /// </summary>
        [EnumMember(Value = "qianfan_bloomz_7b_compressed")]
        Qianfan_BLOOMZ_7B_compressed = 8,

        /// <summary>
        /// Enum Llama_2_7b_chat for value: llama_2_7b
        /// </summary>
        [EnumMember(Value = "llama_2_7b")]
        Llama_2_7b_chat = 9,

        /// <summary>
        /// Enum Llama_2_13b_chat for value: llama_2_13b
        /// </summary>
        [EnumMember(Value = "llama_2_13b")]
        Llama_2_13b_chat = 10,

        /// <summary>
        /// Enum Llama_2_70b_chat for value: llama_2_70b
        /// </summary>
        [EnumMember(Value = "llama_2_70b")]
        Llama_2_70b_chat = 11,

        /// <summary>
        /// Enum Qianfan_Chinese_Llama_2_7B for value: qianfan_chinese_llama_2_7b
        /// </summary>
        [EnumMember(Value = "qianfan_chinese_llama_2_7b")]
        Qianfan_Chinese_Llama_2_7B = 12,

        /// <summary>
        /// Enum Qianfan_Chinese_Llama_2_13B for value: qianfan_chinese_llama_2_13b
        /// </summary>
        [EnumMember(Value = "qianfan_chinese_llama_2_13b")]
        Qianfan_Chinese_Llama_2_13B = 13,

        /// <summary>
        /// Enum ChatGLM2_6B_32K for value: chatglm2_6b_32k
        /// </summary>
        [EnumMember(Value = "chatglm2_6b_32k")]
        ChatGLM2_6B_32K = 14,

        /// <summary>
        /// Enum XuanYuan_70B_Chat_4bit for value: xuanyuan_70b_chat
        /// </summary>
        [EnumMember(Value = "xuanyuan_70b_chat")]
        XuanYuan_70B_Chat_4bit = 15,

        /// <summary>
        /// Enum ChatLaw for value: chatlaw
        /// </summary>
        [EnumMember(Value = "chatlaw")]
        ChatLaw = 16,

        /// <summary>
        /// Enum AquilaChat_7B for value: aquilachat_7b
        /// </summary>
        [EnumMember(Value = "aquilachat_7b")]
        AquilaChat_7B = 17
    }

}
