/*
 * 千帆SDK
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Baiducloud.SDK.Client.FileParameter;
using OpenAPIDateConverter = Baiducloud.SDK.Client.OpenAPIDateConverter;
using Baiducloud.SDK.Client;

namespace Baiducloud.SDK.Model.Qianfan
{
    /// <summary>
    /// Defines CompletionLlmEnum
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum CompletionLlmEnum
    {
        /// <summary>
        /// Enum SQLCoder_7B for value: sqlcoder_7b
        /// </summary>
        [EnumMember(Value = "sqlcoder_7b")]
        SQLCoder_7B = 1,

        /// <summary>
        /// Enum CodeLlama_7b_Instruct for value: codellama_7b_instruct
        /// </summary>
        [EnumMember(Value = "codellama_7b_instruct")]
        CodeLlama_7b_Instruct = 2
    }

}
