/*
 * 千帆SDK
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Baiducloud.SDK.Client.FileParameter;
using OpenAPIDateConverter = Baiducloud.SDK.Client.OpenAPIDateConverter;
using Baiducloud.SDK.Client;

namespace Baiducloud.SDK.Model.Qianfan
{
    /// <summary>
    /// CompletionResponse
    /// </summary>
    [DataContract(Name = "CompletionResponse")]
    public partial class CompletionResponse : IEquatable<CompletionResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CompletionResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CompletionResponse()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="CompletionResponse" /> class.
        /// </summary>
        /// <param name="id">本轮对话的id.</param>
        /// <param name="varObject">回包类型。 completion：文本生成返回.</param>
        /// <param name="created">时间戳.</param>
        /// <param name="sentenceId">表示当前子句的序号。只有在流式接口模式下会返回该字段.</param>
        /// <param name="isEnd">表示当前子句是否是最后一句。只有在流式接口模式下会返回该字段.</param>
        /// <param name="result">对话返回结果.</param>
        /// <param name="isSafe">1：表示输入内容无安全风险 0：表示输入内容有安全风险.</param>
        /// <param name="usage">usage.</param>
        public CompletionResponse(string id = default(string), string varObject = default(string), int created = default(int), int sentenceId = default(int), bool isEnd = default(bool), string result = default(string), int isSafe = default(int), Usage usage = default(Usage))
        {
            this.Id = id;
            this.VarObject = varObject;
            this.Created = created;
            this.SentenceId = sentenceId;
            this.IsEnd = isEnd;
            this.Result = result;
            this.IsSafe = isSafe;
            this.Usage = usage;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// 本轮对话的id
        /// </summary>
        /// <value>本轮对话的id</value>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// 回包类型。 completion：文本生成返回
        /// </summary>
        /// <value>回包类型。 completion：文本生成返回</value>
        [DataMember(Name = "object", EmitDefaultValue = false)]
        public string VarObject { get; set; }

        /// <summary>
        /// 时间戳
        /// </summary>
        /// <value>时间戳</value>
        [DataMember(Name = "created", EmitDefaultValue = false)]
        public int Created { get; set; }

        /// <summary>
        /// 表示当前子句的序号。只有在流式接口模式下会返回该字段
        /// </summary>
        /// <value>表示当前子句的序号。只有在流式接口模式下会返回该字段</value>
        [DataMember(Name = "sentence_id", EmitDefaultValue = false)]
        public int SentenceId { get; set; }

        /// <summary>
        /// 表示当前子句是否是最后一句。只有在流式接口模式下会返回该字段
        /// </summary>
        /// <value>表示当前子句是否是最后一句。只有在流式接口模式下会返回该字段</value>
        [DataMember(Name = "is_end", EmitDefaultValue = true)]
        public bool IsEnd { get; set; }

        /// <summary>
        /// 对话返回结果
        /// </summary>
        /// <value>对话返回结果</value>
        [DataMember(Name = "result", EmitDefaultValue = false)]
        public string Result { get; set; }

        /// <summary>
        /// 1：表示输入内容无安全风险 0：表示输入内容有安全风险
        /// </summary>
        /// <value>1：表示输入内容无安全风险 0：表示输入内容有安全风险</value>
        [DataMember(Name = "is_safe", EmitDefaultValue = false)]
        public int IsSafe { get; set; }

        /// <summary>
        /// Gets or Sets Usage
        /// </summary>
        [DataMember(Name = "usage", EmitDefaultValue = false)]
        public Usage Usage { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CompletionResponse {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  VarObject: ").Append(VarObject).Append("\n");
            sb.Append("  Created: ").Append(Created).Append("\n");
            sb.Append("  SentenceId: ").Append(SentenceId).Append("\n");
            sb.Append("  IsEnd: ").Append(IsEnd).Append("\n");
            sb.Append("  Result: ").Append(Result).Append("\n");
            sb.Append("  IsSafe: ").Append(IsSafe).Append("\n");
            sb.Append("  Usage: ").Append(Usage).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CompletionResponse);
        }

        /// <summary>
        /// Returns true if CompletionResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of CompletionResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CompletionResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.VarObject == input.VarObject ||
                    (this.VarObject != null &&
                    this.VarObject.Equals(input.VarObject))
                ) && 
                (
                    this.Created == input.Created ||
                    this.Created.Equals(input.Created)
                ) && 
                (
                    this.SentenceId == input.SentenceId ||
                    this.SentenceId.Equals(input.SentenceId)
                ) && 
                (
                    this.IsEnd == input.IsEnd ||
                    this.IsEnd.Equals(input.IsEnd)
                ) && 
                (
                    this.Result == input.Result ||
                    (this.Result != null &&
                    this.Result.Equals(input.Result))
                ) && 
                (
                    this.IsSafe == input.IsSafe ||
                    this.IsSafe.Equals(input.IsSafe)
                ) && 
                (
                    this.Usage == input.Usage ||
                    (this.Usage != null &&
                    this.Usage.Equals(input.Usage))
                )
                && (this.AdditionalProperties.Count == input.AdditionalProperties.Count && !this.AdditionalProperties.Except(input.AdditionalProperties).Any());
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                {
                    hashCode = (hashCode * 59) + this.Id.GetHashCode();
                }
                if (this.VarObject != null)
                {
                    hashCode = (hashCode * 59) + this.VarObject.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Created.GetHashCode();
                hashCode = (hashCode * 59) + this.SentenceId.GetHashCode();
                hashCode = (hashCode * 59) + this.IsEnd.GetHashCode();
                if (this.Result != null)
                {
                    hashCode = (hashCode * 59) + this.Result.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.IsSafe.GetHashCode();
                if (this.Usage != null)
                {
                    hashCode = (hashCode * 59) + this.Usage.GetHashCode();
                }
                if (this.AdditionalProperties != null)
                {
                    hashCode = (hashCode * 59) + this.AdditionalProperties.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
