/*
 * 千帆SDK
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Baiducloud.SDK.Client.FileParameter;
using OpenAPIDateConverter = Baiducloud.SDK.Client.OpenAPIDateConverter;
using Baiducloud.SDK.Client;
using System.Reflection;

namespace Baiducloud.SDK.Model.Qianfan
{
    /// <summary>
    /// EmbeddingLlm
    /// </summary>
    [JsonConverter(typeof(EmbeddingLlmJsonConverter))]
    [DataContract(Name = "EmbeddingLlm")]
    public partial class EmbeddingLlm : AbstractOpenAPISchema, IEquatable<EmbeddingLlm>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EmbeddingLlm" /> class
        /// with the <see cref="EmbeddingLlmEnum" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of EmbeddingLlmEnum.</param>
        public EmbeddingLlm(EmbeddingLlmEnum actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EmbeddingLlm" /> class
        /// with the <see cref="string" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of string.</param>
        public EmbeddingLlm(string actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(EmbeddingLlmEnum))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(string))
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: EmbeddingLlmEnum, string");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `EmbeddingLlmEnum`. If the actual instance is not `EmbeddingLlmEnum`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of EmbeddingLlmEnum</returns>
        public EmbeddingLlmEnum GetEmbeddingLlmEnum()
        {
            return (EmbeddingLlmEnum)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `string`. If the actual instance is not `string`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of string</returns>
        public string GetString()
        {
            return (string)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            return JsonConvert.SerializeObject(_actualInstance).Trim('"');
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, EmbeddingLlm.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of EmbeddingLlm
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of EmbeddingLlm</returns>
        public static EmbeddingLlm FromJson(string jsonString)
        {
            EmbeddingLlm newEmbeddingLlm = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newEmbeddingLlm;
            }
            int match = 0;
            List<string> matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(EmbeddingLlmEnum).GetProperty("AdditionalProperties") == null)
                {
                    newEmbeddingLlm = new EmbeddingLlm(JsonConvert.DeserializeObject<EmbeddingLlmEnum>(jsonString, EmbeddingLlm.SerializerSettings));
                }
                else
                {
                    newEmbeddingLlm = new EmbeddingLlm(JsonConvert.DeserializeObject<EmbeddingLlmEnum>(jsonString, EmbeddingLlm.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("EmbeddingLlmEnum");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into EmbeddingLlmEnum: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(string).GetProperty("AdditionalProperties") == null)
                {
                    newEmbeddingLlm = new EmbeddingLlm(JsonConvert.DeserializeObject<string>(jsonString, EmbeddingLlm.SerializerSettings));
                }
                else
                {
                    newEmbeddingLlm = new EmbeddingLlm(JsonConvert.DeserializeObject<string>(jsonString, EmbeddingLlm.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("string");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into string: {1}", jsonString, exception.ToString()));
            }

            if (match == 0)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
            }
            else if (match > 1)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` incorrectly matches more than one schema (should be exactly one match): " + String.Join(",", matchedTypes));
            }

            // deserialization is considered successful at this point if no exception has been thrown.
            return newEmbeddingLlm;
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EmbeddingLlm);
        }

        /// <summary>
        /// Returns true if EmbeddingLlm instances are equal
        /// </summary>
        /// <param name="input">Instance of EmbeddingLlm to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EmbeddingLlm input)
        {
            if (input == null)
                return false;

            return this.ActualInstance.Equals(input.ActualInstance);
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ActualInstance != null)
                    hashCode = hashCode * 59 + this.ActualInstance.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for EmbeddingLlm
    /// </summary>
    public class EmbeddingLlmJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(EmbeddingLlm).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            if(reader.TokenType != JsonToken.Null)
            {
                return EmbeddingLlm.FromJson(JObject.Load(reader).ToString(Formatting.None));
            }
            return null;
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
