/*
 * 千帆SDK
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using Baiducloud.SDK.Client;
using Baiducloud.SDK.Api;
// uncomment below to import models
//using Baiducloud.SDK.Model.Qianfan;

namespace Baiducloud.SDK.Test.Api
{
    /// <summary>
    ///  Class for testing QianfanApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class QianfanApiTests : IDisposable
    {
        private QianfanApi instance;

        public QianfanApiTests()
        {
            instance = new QianfanApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of QianfanApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' QianfanApi
            //Assert.IsType<QianfanApi>(instance);
        }

        /// <summary>
        /// Test Chat
        /// </summary>
        [Fact]
        public void ChatTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ChatLlm llm = null;
            //ChatRequest chatRequest = null;
            //var response = instance.Chat(llm, chatRequest);
            //Assert.IsType<ChatResponse>(response);
        }

        /// <summary>
        /// Test Completion
        /// </summary>
        [Fact]
        public void CompletionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CompletionLlm llm = null;
            //CompletionRequest completionRequest = null;
            //var response = instance.Completion(llm, completionRequest);
            //Assert.IsType<CompletionResponse>(response);
        }

        /// <summary>
        /// Test Embedding
        /// </summary>
        [Fact]
        public void EmbeddingTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //EmbeddingLlm llm = null;
            //EmbeddingRequest embeddingRequest = null;
            //var response = instance.Embedding(llm, embeddingRequest);
            //Assert.IsType<EmbeddingResponse>(response);
        }

        /// <summary>
        /// Test Plugin
        /// </summary>
        [Fact]
        public void PluginTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string serverPath = null;
            //PluginRequest pluginRequest = null;
            //var response = instance.Plugin(serverPath, pluginRequest);
            //Assert.IsType<PluginResponse>(response);
        }

        /// <summary>
        /// Test Text2image
        /// </summary>
        [Fact]
        public void Text2imageTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ImageLlm llm = null;
            //ImageRequest imageRequest = null;
            //var response = instance.Text2image(llm, imageRequest);
            //Assert.IsType<ImageResponse>(response);
        }
    }
}
